### ISSUE TITLE
Capability to detect change on input

### ISSUE THREAD

**Issue by stevef** [jmadler/emoji-picker#101]
Is there an event I can use to detect if the input/textarea has been changed at all, whether directly by the user or via the WYSIWYG editor?

**Comment by philhawthorne** [comment]
Incase someone comes across this issue, there seems to be an option for this. Set `norealTime` to false, which will allow you to see events as the user types in them on `blur`, `change` and `keyup`.

```js
window.emojiPicker = new EmojiPicker({
	emojiable_selector: '[data-emojiable=true]',
	assetsPath: '/mgl/include/emoji-picker-2/img/',
	popupButtonClasses: 'fa fa-smile-o',
	norealTime: false
});
```

**Comment by linktoahref** [comment]
Via the WYSIWYG editor, you can bind an input event handler to the `contenteditable` div

    document.getElementById("editor").addEventListener("input", function() {
        console.log("input event fired");
    }, false);

[Reference](https://stackoverflow.com/a/1411296/5808894)
