### ISSUE TITLE
JQuery is not defined

### ISSUE THREAD

**Issue by nishant679** [jmadler/emoji-picker#148]
**Getting following error**
```
jquery.emojiarea.js:775 Uncaught ReferenceError: jQuery is not defined
    at jquery.emojiarea.js:775 
```

**Comment by AliciaARios** [comment]
did you ever find a resolution?

**Comment by bkunjesh** [comment]
i used 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
in header for jquery
n it worked for me
