### ISSUE TITLE
not working on iphone (but working well on other Apple devices and safari)

### ISSUE THREAD

**Issue by midwiflect** [jmadler/emoji-picker#163]
Hi all
can I get any help? The emojipicker does not work on iphone, but it works well on Ipad and Safari in other apple devices. The demo is working fine on all Apple devices, including iphone, so I am guessing someone has managed to solve this issue, but I cannot find the most up to date code to fix it. 

Can anyone point me in the right direction?

thanks

**Comment by marifuli** [comment]
Hi!
Did you get any error message in the console or something? if yes, pls paste it here.
also can you mention the iphone models that you tried in?

**Comment by midwiflect** [comment]
hi
we did not get error messages at all. Have tried all fixes from prev similar issues (#49 #113 #157) but no success. 
IOs version is 15.5, iphone SE. It works fine after clearing history and website data though

**Comment by marifuli** [comment]
in that case, it should be fine.
for now, i am closing the issue, you can re-open if you want
