### ISSUE TITLE
Not able to acess

### ISSUE THREAD

**Issue by Sid1772** [jmadler/emoji-picker#164]
While using your emoji picker ,When i open the emoji picker the images pallete is not coming up as we are unable to reach the link
https://onesignal.github.io/emoji-picker/lib/img//emoji_spritesheet_0.png  which actually provides the image for the emoji picker.
Rest of the functionality works fine.
The link to acess your image on github gives 404 error and doesnt open up.
This is the image i am getting
![image](https://user-images.githubusercontent.com/88820556/182307980-c64695d0-ed68-4183-b8cf-f024828b8d82.png)

**Comment by marifuli** [comment]
please use the images from your server. using them from the github link is not recommended.
