### ISSUE TITLE
Emoji version in this demo

### ISSUE THREAD

**Issue by midwiflect** [jmadler/emoji-picker#165]
Hi all

does anyone know what is the emoji version used in this picker? I have noticed the selection is quite limited and some new ones are not incorporated. 

Thanks!

**Comment by marifuli** [comment]
hi, 
this is the old version. this repo was abandoned for a long time and we picked it and planing to make it modern. hopefully after 20 Aug, we will be able to publish them 😊

**Comment by midwiflect** [comment]
Thanks for the quick answer. I actually don’t mind if it is the old version, but I would like to know which one it is as I need to reference it (I am using it to capture data for research)

I seemed to remember it was tweetmoji, but I can’t find the reference anymore, any help?

**Comment by midwiflect** [comment]
Thanks for the quick answer. I actually don’t mind if it is the old version, but I would like to know which one it is as I need to reference it (I am using it to capture data for research)

I seemed to remember it was tweetmoji, but I can’t find the reference anymore, any help?


Maria Velo Higueras,

Midwifery Lecturer,

 School of Nursing, Midwifery and Paramedic practice

Robert Gordon University



Please note I am on maternity leave until Summer 2022.



Useful school emails:

***@***.******@***.***> (for student absence reporting)

***@***.******@***.***> (for queries on student travel and expenses)

***@***.******@***.***> (for queries on records / student timesheets / transcripts)

________________________________
From: Md Ariful Islam ***@***.***>
Sent: Friday, August 5, 2022 4:27:10 AM
To: jmadler/emoji-picker ***@***.***>
Cc: Maria Velo Higueras (snmp) ***@***.***>; Author ***@***.***>
Subject: [External] Re: [jmadler/emoji-picker] Emoji version in this demo (Issue #165)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

CAUTION: External sender. Do not click on links or attachments unless you expect them from the sender and know it's safe!
If in doubt please contact the Helpdesk: ***@***.***                +44 (0) 1224 262777


hi,
this is the old version. this repo was abandoned for a long time and we picked it and planing to make it modern. hopefully after 20 Aug, we will be able to publish them 😊

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjmadler%2Femoji-picker%2Fissues%2F165%23issuecomment-1206002132&data=05%7C01%7Cm.velo-higueras%40rgu.ac.uk%7C89402d104c984d54c73708da769262ab%7C51a0a69c0e4f4b3db64212e013198635%7C0%7C0%7C637952668335765209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=k9SHNrnZJ0yL4xcwR8tTd8S1ZDcgZTWdACnokr99k54%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA2EKBLTDHSS5ZJY5HBEJ4DLVXSCY5ANCNFSM55TX5VVA&data=05%7C01%7Cm.velo-higueras%40rgu.ac.uk%7C89402d104c984d54c73708da769262ab%7C51a0a69c0e4f4b3db64212e013198635%7C0%7C0%7C637952668335765209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fgDcFldeCV1DtB7NNcNads8ctB4mAzpW60g3jR5RvJQ%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

[RGU logo. RGU – Scottish University of the Year – The Times Good University Guide 2021]<http://www.rgu.ac.uk>

Robert Gordon University, a Scottish charity registered under charity number SC 013781.

This e-mail and any attachment is for authorised use by the intended recipient(s) only. It may contain proprietary material, confidential information and/or be subject to legal privilege. It should not be copied, disclosed to, retained or used by, any other party. If you are not an intended recipient then please promptly delete this e-mail and any attachment and all copies and inform the sender. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of Robert Gordon University.

Thank you.

**Comment by marifuli** [comment]
sorry, i am not sure what you mean my version. you can check the release page though. https://github.com/jmadler/emoji-picker/releases
